INSERT INTO team (id, name) VALUES (-1, 'Crisp Team');

INSERT INTO team_member (id, first_name, last_name, team_id) VALUES (-53, 'Tomas', 'Björkholm', -1);
INSERT INTO team_member (id, first_name, last_name, team_id) VALUES (-1, 'Alexander', 'Tarnowski', -1);
INSERT INTO team_member (id, first_name, last_name, team_id) VALUES (-8, 'Dan', 'Lagnöhed', -1);
INSERT INTO team_member (id, first_name, last_name, team_id) VALUES (-14, 'Gustav', 'Boström', -1);
INSERT INTO team_member (id, first_name, last_name, team_id) VALUES (-16, 'Henrik', 'Kniberg', -1);
INSERT INTO team_member (id, first_name, last_name, team_id) VALUES (-28, 'Mats', 'Henricson', -1);
INSERT INTO team_member (id, first_name, last_name, team_id) VALUES (-31, 'Mattias', 'Skarin', -1);
INSERT INTO team_member (id, first_name, last_name, team_id) VALUES (-34, 'Mikael', 'Brodd', -1);
INSERT INTO team_member (id, first_name, last_name, team_id) VALUES (-41, 'Ove', 'Näslund', -1);
INSERT INTO team_member (id, first_name, last_name, team_id) VALUES (-42, 'Patrik', 'Linderl', -1);
INSERT INTO team_member (id, first_name, last_name, team_id) VALUES (-45, 'Reza', 'Farhang', -1);
INSERT INTO team_member (id, first_name, last_name, team_id) VALUES (-47, 'Scott', 'Taylor', -1);
INSERT INTO team_member (id, first_name, last_name, team_id) VALUES (-52, 'Thomas', 'Thyberg', -1);
INSERT INTO team_member (id, first_name, last_name, team_id) VALUES (-13, 'Fredrik', 'Lindgren', -1);
INSERT INTO team_member (id, first_name, last_name, team_id) VALUES (-19, 'Jennie', 'Borg', -1);
INSERT INTO team_member (id, first_name, last_name, team_id) VALUES (-21, 'Jimmy', 'Janlén', -1);
INSERT INTO team_member (id, first_name, last_name, team_id) VALUES (-23, 'Lennart', 'Boklund', -1);
INSERT INTO team_member (id, first_name, last_name, team_id) VALUES (-61, 'Martin', 'Christensen', -1);
INSERT INTO team_member (id, first_name, last_name, team_id) VALUES (-29, 'Mats', 'Strandberg', -1);
INSERT INTO team_member (id, first_name, last_name, team_id) VALUES (-32, 'Max', 'Wenzin', -1);
INSERT INTO team_member (id, first_name, last_name, team_id) VALUES (-33, 'Mia', 'Kolmodin', -1);
INSERT INTO team_member (id, first_name, last_name, team_id) VALUES (-39, 'Olle', 'Hallin', -1);
INSERT INTO team_member (id, first_name, last_name, team_id) VALUES (-40, 'Oscar', 'Lantz', -1);
INSERT INTO team_member (id, first_name, last_name, team_id) VALUES (-43, 'Per', 'Lundholm', -1);
INSERT INTO team_member (id, first_name, last_name, team_id) VALUES (-44, 'Peter', 'Antman', -1);
INSERT INTO team_member (id, first_name, last_name, team_id) VALUES (-55, 'Yassal', 'Sundman', -1);
INSERT INTO team_member (id, first_name, last_name, team_id) VALUES (-80, 'Michael', 'Göthe', -1);
INSERT INTO team_member (id, first_name, last_name, team_id) VALUES (-9, 'Daniel', 'Sundman', -1);
INSERT INTO team_member (id, first_name, last_name, team_id) VALUES (-56, 'Fatima', 'Hasselbom', -1);
INSERT INTO team_member (id, first_name, last_name, team_id) VALUES (-75, 'Elin', 'Ayani', -1);
INSERT INTO team_member (id, first_name, last_name, team_id) VALUES (-73, 'Eva Maria', 'Matell', -1);
INSERT INTO team_member (id, first_name, last_name, team_id) VALUES (-18, 'Jan', 'Grape', -1);
INSERT INTO team_member (id, first_name, last_name, team_id) VALUES (-2, 'Anders', 'Laestadius', -1);
INSERT INTO team_member (id, first_name, last_name, team_id) VALUES (-10, 'David', 'Barnholdt', -1);
INSERT INTO team_member (id, first_name, last_name, team_id) VALUES (-15, 'Hans', 'Brattberg', -1);
INSERT INTO team_member (id, first_name, last_name, team_id) VALUES (-24, 'Magnus', 'Axelqvist', -1);

